In [1]:
import pandas as pd
import os
from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

C:\Users\Dell\Desktop\ML\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ROOT_DIR = os.path.abspath(os.path.join(os.path.join(os.getcwd(), ".."), ".."))
DATA_DIR = os.path.join(ROOT_DIR, "Data")
DATASET_DIR = os.path.join(DATA_DIR, "SMS-Spam-Data")
DATASET_FILE = os.path.join(DATASET_DIR, "Dataset_5971.csv")

In [3]:
df = pd.read_csv(DATASET_FILE)
df.head()

      LABEL                                               TEXT URL EMAIL PHONE
0       ham  Your opinion about me? 1. Over 2. Jada 3. Kusr...  No    No    No
1       ham  What's up? Do you want me to come online? If y...  No    No    No
2       ham                       So u workin overtime nigpun?  No    No    No
3       ham  Also sir, i sent you an email about how to log...  No    No    No
4  Smishing  Please Stay At Home. To encourage the notion o...  No    No    No

In [4]:
df["TEXT"] = df["TEXT"].str.lstrip("\t")
df["CLEAN"] = df["TEXT"].str.lower().str.split().str.join(" ")
df["LABEL"] = df["LABEL"].str.strip().str.lower()
df = df.drop_duplicates(subset="CLEAN").drop(columns="CLEAN")
df.shape

(5831, 5)

## Raw text, no `<PHONE>`/`<URL>` masking

Unlike the Baseline/NN/CNN notebooks, this one skips the placeholder masking. A pretrained
sentence encoder has already seen phone numbers and URLs in its own pretraining data and
tokenizes them fine on its own; masking them to `<PHONE>`/`<URL>` would throw away
information the encoder could otherwise use, for no benefit specific to this model.

In [5]:
X = df["TEXT"]
y = df["LABEL"]

In [6]:
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.1, stratify=y_temp, random_state=42)

In [7]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_val_encoded = encoder.transform(y_val)
y_test_encoded = encoder.transform(y_test)

## Frozen sentence embeddings

`all-MiniLM-L6-v2` as a feature extractor only - no fine-tuning, no gradient ever touches
its weights. First run downloads the model from the Hugging Face Hub (~90MB, cached
locally afterward, needs internet once).

In [8]:
embedder = SentenceTransformer("all-MiniLM-L6-v2")

X_train_emb = embedder.encode(X_train.tolist(), show_progress_bar=True)
X_val_emb = embedder.encode(X_val.tolist(), show_progress_bar=True)
X_test_emb = embedder.encode(X_test.tolist(), show_progress_bar=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4891.12it/s]

Batches:   0%|          | 0/132 [00:00<?, ?it/s]

Batches:   1%|          | 1/132 [00:00<02:06,  1.04it/s]

Batches:   2%|▏         | 2/132 [00:01<01:17,  1.68it/s]

Batches:   2%|▏         | 3/132 [00:01<00:57,  2.25it/s]

Batches:   3%|▎         | 4/132 [00:01<00:47,  2.69it/s]

Batches:   4%|▍         | 5/132 [00:02<00:40,  3.17it/s]

Batches:   5%|▍         | 6/132 [00:02<00:35,  3.53it/s]

Batches:   5%|▌         | 7/132 [00:02<00:32,  3.88it/s]

Batches:   6%|▌         | 8/132 [00:02<00:28,  4.32it/s]

Batches:   7%|▋         | 9/132 [00:02<00:28,  4.37it/s]

Batches:   8%|▊         | 10/132 [00:03<00:37,  3.26it/s]

Batches:   8%|▊         | 11/132 [00:03<00:49,  2.46it/s]

Batches:   9%|▉         | 12/132 [00:04<00:57,  2.10it/s]

Batches:  10%|▉         | 13/132 [00:05<01:04,  1.85it/s]

Batches:  11%|█         | 14/132 [00:05<01:08,  1.71it/s]

Batches:  11%|█▏        | 15/132 [00:06<01:11,  1.63it/s]

Batches:  12%|█▏        | 16/132 [00:07<01:10,  1.64it/s]

Batches:  13%|█▎        | 17/132 [00:07<01:09,  1.65it/s]

Batches:  14%|█▎        | 18/132 [00:08<01:10,  1.61it/s]

Batches:  14%|█▍        | 19/132 [00:09<01:09,  1.63it/s]

Batches:  15%|█▌        | 20/132 [00:09<01:05,  1.72it/s]

Batches:  16%|█▌        | 21/132 [00:10<01:09,  1.59it/s]

Batches:  17%|█▋        | 22/132 [00:11<01:10,  1.56it/s]

Batches:  17%|█▋        | 23/132 [00:11<01:12,  1.51it/s]

Batches:  18%|█▊        | 24/132 [00:12<01:09,  1.55it/s]

Batches:  19%|█▉        | 25/132 [00:13<01:09,  1.53it/s]

Batches:  20%|█▉        | 26/132 [00:13<01:10,  1.50it/s]

Batches:  20%|██        | 27/132 [00:14<01:12,  1.44it/s]

Batches:  21%|██        | 28/132 [00:15<01:08,  1.53it/s]

Batches:  22%|██▏       | 29/132 [00:15<01:05,  1.58it/s]

Batches:  23%|██▎       | 30/132 [00:16<01:03,  1.60it/s]

Batches:  23%|██▎       | 31/132 [00:16<01:00,  1.66it/s]

Batches:  24%|██▍       | 32/132 [00:17<00:54,  1.85it/s]

Batches:  25%|██▌       | 33/132 [00:17<00:53,  1.84it/s]

Batches:  26%|██▌       | 34/132 [00:18<00:50,  1.95it/s]

Batches:  27%|██▋       | 35/132 [00:18<00:49,  1.98it/s]

Batches:  27%|██▋       | 36/132 [00:19<00:46,  2.06it/s]

Batches:  28%|██▊       | 37/132 [00:19<00:45,  2.09it/s]

Batches:  29%|██▉       | 38/132 [00:19<00:43,  2.17it/s]

Batches:  30%|██▉       | 39/132 [00:20<00:42,  2.17it/s]

Batches:  30%|███       | 40/132 [00:20<00:41,  2.24it/s]

Batches:  31%|███       | 41/132 [00:21<00:42,  2.13it/s]

Batches:  32%|███▏      | 42/132 [00:21<00:41,  2.17it/s]

Batches:  33%|███▎      | 43/132 [00:22<00:39,  2.24it/s]

Batches:  33%|███▎      | 44/132 [00:22<00:37,  2.32it/s]

Batches:  34%|███▍      | 45/132 [00:22<00:35,  2.46it/s]

Batches:  35%|███▍      | 46/132 [00:23<00:35,  2.42it/s]

Batches:  36%|███▌      | 47/132 [00:23<00:37,  2.25it/s]

Batches:  36%|███▋      | 48/132 [00:24<00:37,  2.26it/s]

Batches:  37%|███▋      | 49/132 [00:24<00:35,  2.35it/s]

Batches:  38%|███▊      | 50/132 [00:25<00:32,  2.49it/s]

Batches:  39%|███▊      | 51/132 [00:25<00:30,  2.69it/s]

Batches:  39%|███▉      | 52/132 [00:25<00:28,  2.77it/s]

Batches:  40%|████      | 53/132 [00:26<00:29,  2.72it/s]

Batches:  41%|████      | 54/132 [00:26<00:27,  2.86it/s]

Batches:  42%|████▏     | 55/132 [00:26<00:26,  2.93it/s]

Batches:  42%|████▏     | 56/132 [00:27<00:25,  2.95it/s]

Batches:  43%|████▎     | 57/132 [00:27<00:24,  3.08it/s]

Batches:  44%|████▍     | 58/132 [00:27<00:24,  3.01it/s]

Batches:  45%|████▍     | 59/132 [00:28<00:24,  3.02it/s]

Batches:  45%|████▌     | 60/132 [00:28<00:23,  3.01it/s]

Batches:  46%|████▌     | 61/132 [00:28<00:22,  3.20it/s]

Batches:  47%|████▋     | 62/132 [00:28<00:20,  3.47it/s]

Batches:  48%|████▊     | 63/132 [00:29<00:20,  3.40it/s]

Batches:  48%|████▊     | 64/132 [00:29<00:22,  3.02it/s]

Batches:  49%|████▉     | 65/132 [00:29<00:21,  3.16it/s]

Batches:  50%|█████     | 66/132 [00:30<00:19,  3.31it/s]

Batches:  51%|█████     | 67/132 [00:30<00:18,  3.47it/s]

Batches:  52%|█████▏    | 68/132 [00:30<00:18,  3.54it/s]

Batches:  52%|█████▏    | 69/132 [00:30<00:17,  3.65it/s]

Batches:  53%|█████▎    | 70/132 [00:31<00:16,  3.80it/s]

Batches:  54%|█████▍    | 71/132 [00:31<00:15,  3.89it/s]

Batches:  55%|█████▍    | 72/132 [00:31<00:14,  4.03it/s]

Batches:  55%|█████▌    | 73/132 [00:31<00:13,  4.23it/s]

Batches:  56%|█████▌    | 74/132 [00:32<00:12,  4.48it/s]

Batches:  57%|█████▋    | 75/132 [00:32<00:12,  4.55it/s]

Batches:  58%|█████▊    | 76/132 [00:32<00:12,  4.33it/s]

Batches:  58%|█████▊    | 77/132 [00:32<00:12,  4.47it/s]

Batches:  59%|█████▉    | 78/132 [00:32<00:12,  4.45it/s]

Batches:  60%|█████▉    | 79/132 [00:33<00:11,  4.71it/s]

Batches:  61%|██████    | 80/132 [00:33<00:10,  4.93it/s]

Batches:  61%|██████▏   | 81/132 [00:33<00:10,  4.97it/s]

Batches:  62%|██████▏   | 82/132 [00:33<00:10,  4.99it/s]

Batches:  63%|██████▎   | 83/132 [00:33<00:09,  4.98it/s]

Batches:  64%|██████▎   | 84/132 [00:34<00:10,  4.52it/s]

Batches:  64%|██████▍   | 85/132 [00:34<00:10,  4.60it/s]

Batches:  65%|██████▌   | 86/132 [00:34<00:09,  4.99it/s]

Batches:  66%|██████▌   | 87/132 [00:34<00:09,  4.78it/s]

Batches:  67%|██████▋   | 88/132 [00:34<00:08,  4.95it/s]

Batches:  67%|██████▋   | 89/132 [00:35<00:08,  4.92it/s]

Batches:  68%|██████▊   | 90/132 [00:35<00:08,  5.01it/s]

Batches:  69%|██████▉   | 91/132 [00:35<00:07,  5.20it/s]

Batches:  70%|██████▉   | 92/132 [00:35<00:07,  5.34it/s]

Batches:  70%|███████   | 93/132 [00:35<00:07,  5.47it/s]

Batches:  71%|███████   | 94/132 [00:36<00:07,  5.16it/s]

Batches:  72%|███████▏  | 95/132 [00:36<00:06,  5.36it/s]

Batches:  73%|███████▎  | 96/132 [00:36<00:07,  5.07it/s]

Batches:  73%|███████▎  | 97/132 [00:36<00:06,  5.40it/s]

Batches:  74%|███████▍  | 98/132 [00:36<00:06,  5.18it/s]

Batches:  75%|███████▌  | 99/132 [00:37<00:06,  5.33it/s]

Batches:  76%|███████▌  | 100/132 [00:37<00:06,  5.33it/s]

Batches:  77%|███████▋  | 101/132 [00:37<00:05,  5.57it/s]

Batches:  77%|███████▋  | 102/132 [00:37<00:05,  5.81it/s]

Batches:  78%|███████▊  | 103/132 [00:37<00:04,  6.01it/s]

Batches:  79%|███████▉  | 104/132 [00:37<00:04,  6.10it/s]

Batches:  80%|███████▉  | 105/132 [00:38<00:04,  6.22it/s]

Batches:  80%|████████  | 106/132 [00:38<00:04,  5.98it/s]

Batches:  81%|████████  | 107/132 [00:38<00:04,  6.08it/s]

Batches:  82%|████████▏ | 108/132 [00:38<00:03,  6.07it/s]

Batches:  83%|████████▎ | 109/132 [00:38<00:03,  6.02it/s]

Batches:  83%|████████▎ | 110/132 [00:38<00:03,  6.14it/s]

Batches:  84%|████████▍ | 111/132 [00:38<00:03,  6.54it/s]

Batches:  85%|████████▍ | 112/132 [00:39<00:03,  6.50it/s]

Batches:  86%|████████▌ | 113/132 [00:39<00:02,  6.46it/s]

Batches:  86%|████████▋ | 114/132 [00:39<00:02,  6.59it/s]

Batches:  87%|████████▋ | 115/132 [00:39<00:02,  6.72it/s]

Batches:  88%|████████▊ | 116/132 [00:39<00:02,  6.80it/s]

Batches:  89%|████████▊ | 117/132 [00:39<00:02,  6.80it/s]

Batches:  89%|████████▉ | 118/132 [00:40<00:02,  6.82it/s]

Batches:  90%|█████████ | 119/132 [00:40<00:01,  7.30it/s]

Batches:  91%|█████████ | 120/132 [00:40<00:01,  7.63it/s]

Batches:  92%|█████████▏| 121/132 [00:40<00:01,  7.44it/s]

Batches:  92%|█████████▏| 122/132 [00:40<00:01,  7.42it/s]

Batches:  93%|█████████▎| 123/132 [00:40<00:01,  7.38it/s]

Batches:  94%|█████████▍| 124/132 [00:40<00:01,  7.14it/s]

Batches:  95%|█████████▍| 125/132 [00:40<00:00,  7.32it/s]

Batches:  95%|█████████▌| 126/132 [00:41<00:00,  7.56it/s]

Batches:  96%|█████████▌| 127/132 [00:41<00:00,  7.81it/s]

Batches:  97%|█████████▋| 128/132 [00:41<00:00,  7.65it/s]

Batches:  98%|█████████▊| 129/132 [00:41<00:00,  7.42it/s]

Batches:  98%|█████████▊| 130/132 [00:41<00:00,  7.61it/s]

Batches:  99%|█████████▉| 131/132 [00:41<00:00,  7.80it/s]

Batches: 100%|██████████| 132/132 [00:41<00:00,  3.16it/s]

Batches:   0%|          | 0/15 [00:00<?, ?it/s]

Batches:   7%|▋         | 1/15 [00:01<00:14,  1.00s/it]

Batches:  13%|█▎        | 2/15 [00:01<00:09,  1.38it/s]

Batches:  20%|██        | 3/15 [00:02<00:07,  1.57it/s]

Batches:  27%|██▋       | 4/15 [00:02<00:06,  1.74it/s]

Batches:  33%|███▎      | 5/15 [00:03<00:05,  1.81it/s]

Batches:  40%|████      | 6/15 [00:03<00:04,  1.89it/s]

Batches:  47%|████▋     | 7/15 [00:04<00:04,  1.67it/s]

Batches:  53%|█████▎    | 8/15 [00:04<00:03,  1.94it/s]

Batches:  60%|██████    | 9/15 [00:05<00:02,  2.12it/s]

Batches:  67%|██████▋   | 10/15 [00:05<00:01,  2.58it/s]

Batches:  73%|███████▎  | 11/15 [00:05<00:01,  3.10it/s]

Batches:  80%|████████  | 12/15 [00:05<00:00,  3.64it/s]

Batches:  87%|████████▋ | 13/15 [00:05<00:00,  4.25it/s]

Batches:  93%|█████████▎| 14/15 [00:05<00:00,  4.87it/s]

Batches: 100%|██████████| 15/15 [00:05<00:00,  5.57it/s]

Batches: 100%|██████████| 15/15 [00:05<00:00,  2.52it/s]

Batches:   0%|          | 0/37 [00:00<?, ?it/s]

Batches:   3%|▎         | 1/37 [00:02<01:16,  2.12s/it]

Batches:   5%|▌         | 2/37 [00:02<00:42,  1.22s/it]

Batches:   8%|▊         | 3/37 [00:03<00:32,  1.04it/s]

Batches:  11%|█         | 4/37 [00:03<00:26,  1.23it/s]

Batches:  14%|█▎        | 5/37 [00:04<00:23,  1.37it/s]

Batches:  16%|█▌        | 6/37 [00:05<00:21,  1.43it/s]

Batches:  19%|█▉        | 7/37 [00:05<00:20,  1.50it/s]

Batches:  22%|██▏       | 8/37 [00:06<00:18,  1.58it/s]

Batches:  24%|██▍       | 9/37 [00:06<00:16,  1.69it/s]

Batches:  27%|██▋       | 10/37 [00:07<00:15,  1.73it/s]

Batches:  30%|██▉       | 11/37 [00:07<00:14,  1.84it/s]

Batches:  32%|███▏      | 12/37 [00:08<00:12,  2.02it/s]

Batches:  35%|███▌      | 13/37 [00:08<00:11,  2.13it/s]

Batches:  38%|███▊      | 14/37 [00:08<00:09,  2.38it/s]

Batches:  41%|████      | 15/37 [00:09<00:08,  2.55it/s]

Batches:  43%|████▎     | 16/37 [00:09<00:07,  2.75it/s]

Batches:  46%|████▌     | 17/37 [00:09<00:06,  3.03it/s]

Batches:  49%|████▊     | 18/37 [00:10<00:05,  3.32it/s]

Batches:  51%|█████▏    | 19/37 [00:10<00:05,  3.50it/s]

Batches:  54%|█████▍    | 20/37 [00:10<00:04,  3.58it/s]

Batches:  57%|█████▋    | 21/37 [00:10<00:04,  3.77it/s]

Batches:  59%|█████▉    | 22/37 [00:10<00:03,  4.08it/s]

Batches:  62%|██████▏   | 23/37 [00:11<00:03,  4.36it/s]

Batches:  65%|██████▍   | 24/37 [00:11<00:02,  4.56it/s]

Batches:  68%|██████▊   | 25/37 [00:11<00:02,  4.57it/s]

Batches:  70%|███████   | 26/37 [00:11<00:02,  4.95it/s]

Batches:  73%|███████▎  | 27/37 [00:11<00:01,  5.15it/s]

Batches:  76%|███████▌  | 28/37 [00:12<00:01,  5.01it/s]

Batches:  78%|███████▊  | 29/37 [00:12<00:01,  4.91it/s]

Batches:  81%|████████  | 30/37 [00:12<00:01,  5.25it/s]

Batches:  84%|████████▍ | 31/37 [00:12<00:01,  5.53it/s]

Batches:  86%|████████▋ | 32/37 [00:12<00:00,  5.64it/s]

Batches:  89%|████████▉ | 33/37 [00:13<00:00,  5.86it/s]

Batches:  92%|█████████▏| 34/37 [00:13<00:00,  6.02it/s]

Batches:  95%|█████████▍| 35/37 [00:13<00:00,  6.12it/s]

Batches:  97%|█████████▋| 36/37 [00:13<00:00,  6.44it/s]

Batches: 100%|██████████| 37/37 [00:13<00:00,  2.74it/s]

In [9]:
model = LogisticRegression(class_weight="balanced", max_iter=1000)
model.fit(X_train_emb, y_train_encoded)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [10]:
y_val_pred = model.predict(X_val_emb)
print(classification_report(y_val_encoded, y_val_pred, target_names=encoder.classes_, zero_division=0, digits=3))

              precision    recall  f1-score   support

         ham      0.982     0.972     0.977       387
    smishing      0.881     0.841     0.860        44
        spam      0.643     0.750     0.692        36

    accuracy                          0.942       467
   macro avg      0.835     0.854     0.843       467
weighted avg      0.946     0.942     0.944       467

In [11]:
y_pred = model.predict(X_test_emb)
print(classification_report(y_test_encoded, y_pred, target_names=encoder.classes_, zero_division=0, digits=3))

              precision    recall  f1-score   support

         ham      0.992     0.967     0.979       967
    smishing      0.783     0.927     0.849       109
        spam      0.737     0.769     0.753        91

    accuracy                          0.948      1167
   macro avg      0.837     0.888     0.860      1167
weighted avg      0.952     0.948     0.949      1167

In [12]:
conf_matrix = confusion_matrix(y_test_encoded, y_pred)
print(conf_matrix)

[[935  14  18]
 [  1 101   7]
 [  7  14  70]]

In [13]:
results = pd.DataFrame({
    "text": X_test.to_numpy(),
    "true": encoder.inverse_transform(y_test_encoded),
    "pred": encoder.inverse_transform(y_pred),
})

error = results[results["true"] != results["pred"]]
error

                                                   text  true      pred
12    Plz note: if anyone calling from a mobile Co. ...   ham  smishing
25    Can you plz tell me the answer. Reeta sent via...   ham      spam
82    Had the money issue weigh me down but thanks t...   ham      spam
98    ROMCA Everyone around should be responding wel...  spam       ham
125   No message..no response..what happend? Any iss...   ham  smishing
...                                                 ...   ...       ...
1088  No problem with the renewal. I.ll do it right ...   ham      spam
1108  Do you want a New Nokia 3510i colour phone Del...  spam  smishing
1109  Thank You for calling.Forgot to say Happy Onam...   ham  smishing
1128  We know someone who you know that fancies you....  spam  smishing
1156  Went to pay rent. So i had to go to the bank t...   ham  smishing

[61 rows x 3 columns]